# Architecture identifier.
arch = "aarch64"                    # str
# Platform identifier.
platform = "aarch64-rk3588j"        # str
# Platform package.
package = "axplat-aarch64-rk3588j"            # str


#
# Platform configs
#
[plat]
# Number of CPUs.
cpu-num = 8                         # uint
# Base address of the whole physical memory.
phys-memory-base = 0x20_0000        # uint
# Size of the whole physical memory.
phys-memory-size = 0x800_0000       # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x40_0000       # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_0040_0000"     # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"      # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0                             # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_0000_0000_0000"    # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_ffff_ffff_f000"    # uint
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000                       # uint

# PSCI
psci-method = "smc"

# CPU Hardware ID list
cpu-id-list = [0x00, 0x100, 0x200, 0x300, 0x400, 0x500, 0x600, 0x700]


[devices]
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [
    [0xfeb50000, 0x1000], # uart8250 UART0
    [0xfe600000, 0x10000], # gic-v3 gicd
    [0xfe680000, 0x100000], # gic-v3 gicr
    [0xa41000000, 0x400000],
    [0xa40c00000, 0x400000],
    [0xf4000000, 0x1000000],
    [0xf3000000, 0x1000000],
]   # [(uint, uint)]
# VirtIO MMIO ranges with format (`base_paddr`, `size`).
virtio-mmio-ranges = []                        # [(uint, uint)]

# Base physical address of the PCIe ECAM space.
pci-ecam-base = "0xf4000000"                    # uint
# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = "0xff"                            # uint
# PCI device memory ranges (`ranges` property in device tree).
pci-ranges = []                                 # [(uint, uint)]
# UART Address
uart-paddr = "0xfeb5_0000"                      # uint
uart-irq = "0x14d"                              # uint
timer-irq = "0x1e"                                # uint

# GICC Address
gicd-paddr = "0xfe600000"                       # uint  
# GICR Address
gicr-paddr = "0xfe680000"                       # uint